# Generated by Django 3.1.7 on 2021-03-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='@Example_13-65 new jersey'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='You bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.TextField(default='@Example_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default='@Example_045978346'),
        ),
    ]
