# Generated by Django 3.1.7 on 2021-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.CharField(default='A', max_length=20),
            preserve_default=False,
        ),
    ]
