# Generated by Django 3.1.7 on 2021-03-06 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
