# Generated by Django 3.1.7 on 2021-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bets',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
