# Generated by Django 3.1.7 on 2021-03-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210313_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bets',
            options={'verbose_name': 'Bet', 'verbose_name_plural': 'Bets'},
        ),
    ]
