# Generated by Django 3.1.7 on 2021-03-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210313_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
