# Generated by Django 3.1.7 on 2021-03-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.auctionitem'),
        ),
    ]
