# Generated by Django 3.1.7 on 2021-03-16 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210316_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='color',
            field=models.CharField( max_length=50),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='model',
            field=models.CharField( max_length=50),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='location',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
    ]
