# Generated by Django 3.1.7 on 2021-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210317_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_cat', upload_to='Category_pics'),
        ),
    ]
