# Generated by Django 3.1.7 on 2021-03-19 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_follower_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followers',
        ),
        migrations.AddField(
            model_name='follower',
            name='followed_by',
            field=models.ForeignKey(default=565, on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
